#General
name: Test
version: 0.1
releaseDate: 1/1/2005
locale: EN
messageBundle: yml

# Api Server
server:
  port: 8070
  context-path: /api

# Database
db:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5439/postgres
  username: postgres
  password: admin

# Hibernate
hibernate:
  dialect: org.hibernate.dialect.PostgreSQL82Dialect
  show_sql: true
  hbm2ddl.auto: update


